### ISSUE TITLE
OSError: ./weights/weights_0.1.csv not found.

### ISSUE THREAD

**Issue by mcdonaldnj304** [hirokatsukataoka16/FractalDB#3]
Good Morning,

After finishing the Fractal Category Search I proceeded to run the code fractal_renderer/make_fractaldb.py to construct FractalDB. However, in doing so I receive an error:   
$ python fractal_renderer/make_fractaldb.py
Traceback (most recent call last):
  File "fractal_renderer/make_fractaldb.py", line 39, in <module>
    weights = np.genfromtxt(args.weight_csv,dtype=np.str,delimiter=',')
  File "/home/noahm/RSML/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1772, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/noahm/RSML/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/noahm/RSML/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: ./weights/weights_0.1.csv not found.

I went to FractalDB-trained-ResNet-PyTorch/fractal_renderer/weights and found the file weights_0.1.csv was indeed there.
I am unsure of the solution to this problem.

**Comment by rakshak-t** [comment]
@mcdonaldnj304 

You can explicitly specify the path as I've shown here.

`python3 fractal_renderer make_fractaldb.py  <YOUR_OTHER_ARGS> --weight_csv <YOUR_PATH>/FractalDB-Pretrained-ResNet-PyTorch/fractal_renderer/weights/weights_0.1.csv`
